# Quelle: [Klein et al., 2018]
# Quelle: [Koehn, 2005]
# Quelle: [OpenNMT, o. D.a]
# Quelle: [OpenNMT, o. D.b]
# Quelle: [OpenNMT, o. D.c]
# Quelle: [OPUS, o. D.]
# Quelle: [Tiedemann, 2012]


# europarl.yaml

# Wo die Vokabular-Dateien gespeichert werden
save_data: OpenNMT-vocab-data
# Wo das Vokabular gespeichert werden soll
src_vocab: OpenNMT-vocab-data/openmten.vocab.src
tgt_vocab: OpenNMT-vocab-data/openmtde.vocab.tgt

# Corpus opts:
data:
    corpus_1:
        path_src: Data/Europarl.de-en.en-filtered.en.subword.train
        path_tgt: Data/Europarl.de-en.de-filtered.de.subword.train
    valid:
        path_src: Data/Europarl.de-en.en-filtered.en.subword.dev
        path_tgt: Data/Europarl.de-en.de-filtered.de.subword.dev

# Vokabular-Dateien, die gerade erstellt wurden
src_vocab: OpenNMT-vocab-data/openmten.vocab.src
tgt_vocab: OpenNMT-vocab-data/openmtde.vocab.tgt

# General opts
save_model: NMT-Model/model_batch_size_2k
save_checkpoint_steps: 5000
train_steps: 100000
valid_steps: 2000
report_every: 100

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 2000
valid_batch_size: 256
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]